services:
  backend:
    image: 235494806540.dkr.ecr.eu-central-1.amazonaws.com/property-management-app/backend:latest
    container_name: property_backend
    env_file:
      - ./.env.prod
    expose:
      - 8000

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
