services:
  db:
    image: postgres:17-alpine
    container_name: property_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - property_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U property_user -d property_database"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  property_data:
