apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: property-app
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: migrate-db
          image: blagojaovezoski/property-backend:latest
          command: ["python", "manage.py", "migrate"]
          env:
            - name: DJANGO_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: property-secrets
                  key: POSTGRES_DB
            - name: DJANGO_DB_USER
              valueFrom:
                secretKeyRef:
                  name: property-secrets
                  key: POSTGRES_USER
            - name: DJANGO_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: property-secrets
                  key: POSTGRES_PASSWORD
            - name: DJANGO_DB_HOST
              value: postgres-service
            - name: DJANGO_DB_PORT
              value: "5432"
      containers:
        - name: django-backend
          image: blagojaovezoski/property-backend:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: property-secrets
            - configMapRef:
                name: property-config
          env:
            - name: DJANGO_DB_HOST
              value: postgres-service
            - name: DJANGO_DB_PORT
              value: "5432"
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: DJANGO_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: property-secrets
                  key: POSTGRES_DB
            - name: DJANGO_DB_USER
              valueFrom:
                secretKeyRef:
                  name: property-secrets
                  key: POSTGRES_USER
            - name: DJANGO_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: property-secrets
                  key: POSTGRES_PASSWORD
            - name: FORCE_RELOAD_TIMESTAMP
              value: "2025-06-27-1545"

          # TODO: use Gunicorn/uWSGI in production.
          # entrypoint: ["/usr/local/bin/gunicorn"]
          # args: ["project.wsgi:application", "--bind", "0.0.0.0:8000"]
          command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
