# Generated by Django 5.2.3 on 2025-07-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0003_property_main_image_alter_property_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="address_line_1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="address_line_2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="state_province",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="zip_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
