# Generated by Django 5.2.3 on 2025-07-12 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0004_property_address_line_1_property_address_line_2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="property.property"
            ),
        ),
    ]
