apiVersion: v1
kind: ConfigMap
metadata:
  name: property-config
  namespace: property-app
data:
  ALLOWED_HOSTS: "backend.property-app.svc.cluster.local,localhost,127.0.0.1,10.42.0.0/16,api.local"
  DEBUG: "False"
  VITE_API_BASE_URL: "http://api.local"
