name: Backend CI - Build and Push Image

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yml"
  pull_request:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yml"

jobs:
  build_and_push_backend:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.vars.outputs.sha }}
      backend_image_tag: ${{ steps.backend_build.outputs.tags }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get short Git SHA
        id: vars
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Configure AWS credentials for ECR access (Backend)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR (Backend)
        id: login-ecr-backend
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Django backend image to ECR
        id: backend_build
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ${{ steps.login-ecr-backend.outputs.registry }}/${{ secrets.ECR_REPOSITORY_BACKEND }}:${{ steps.vars.outputs.sha }}
            ${{ steps.login-ecr-backend.outputs.registry }}/${{ secrets.ECR_REPOSITORY_BACKEND }}:latest
